# arguments for dataset
dataset: potsdam
nclass: 6
crop_size: 512
data_root: /data1/potsdam/

# arguments for training
epochs: 80
batch_size: 2
lr: 0.001  # 2GPUs
lr_multi: 10.0
criterion:
  name: CELoss
  kwargs:
    ignore_index: 255
conf_thresh: 0.95

# arguments for model
model: deeplabv3plus
backbone: resnet50
replace_stride_with_dilation: [False, False, True]
dilations: [6, 12, 18]
